#!/bin/sh

# Get API key from environment variables
API_KEY="${GROQ_API_KEY:-${OPENAI_API_KEY:-}}"

if [ -z "$API_KEY" ]; then
    echo "ERROR: No API key found. Set GROQ_API_KEY or OPENAI_API_KEY environment variable."
    exit 1
fi

echo "INFO: Starting LLM Groq Proxy v1.2"
echo "INFO: API key configured (${#API_KEY} characters)"

# Create nginx configuration with API key substitution
cat > /tmp/nginx_vars.conf << EOF
# This file is auto-generated by entrypoint.sh
map \$host \$groq_api_key {
    default "$API_KEY";
}
EOF

# Insert the map block into nginx.conf before the server block
sed -i '/^http {/r /tmp/nginx_vars.conf' /etc/nginx/nginx.conf

# Test nginx configuration
nginx -t
if [ $? -ne 0 ]; then
    echo "ERROR: Nginx configuration test failed"
    exit 1
fi

echo "INFO: Nginx configuration valid"
echo "INFO: Starting nginx..."

# Start nginx in foreground
exec nginx -g "daemon off;"